# Configurations for LIST Web Server
# Use this file for development mode

# Filesystem related
folder: /home/ebu/tmp/list/
cpp: /home/ebu/list/live/cmake-build-debug/third_party/ebu_list/bin/

# HTTP-related
cookieSecret: STRD4O
webappDomain: http://localhost:8080

# MongoDB database
database:
  hostname: localhost
  port: 27017

# InfluxDB URL
influx:
  hostname: localhost
  port: 8086

nmosRegistry:
  hostname: localhost
  port: 8082
  version: 1.2
  refresh: 1
